title: Arani Boire(AB)
#logo:
description: Accomplished data scientist with 3+ years of experience delivering high-impact solutions. Skilled in advanced machine learning, statistical analysis, and scalable Python development, transform raw data into actionable insights that drive business growth. Thrive in fast-paced environments, leveraging strong communication and leadership to empower team success.
show_downloads: true
theme: jekyll-theme-minimal

